on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: dotnet new console
      - run: dotnet pack
      - run: |
          dotnet tool update gpr -g
          gpr push bin/Debug --repository ${{ github.repository }} --version 1.0.0-changed -k ${{ github.token }}
